#! /bin/zsh
. $HOME/.xmonad/.xmobar/icons
#if [ -e /usr/bin/xbacklight -get ]; then
# read the status from file (0 = max brightness, 7 = min brightness)
BACK_STAT=$(/usr/bin/xbacklight -get)
# convert to fake percentage: 100 = max, 30 = min
#BACK_BRT=$(echo $((100 - (10 * $BACK_STAT))))
BACK_BRT=${BACK_STAT%\.*}
echo -e "<fc=#4286f4>$ICON_BACKLIGHT $BACK_BRT</fc>"
#fi
